spring:
  application:
    name: ecommerce-Multivendor
  mail:
    host: smtp.gmail.com
    port: 587
    username: tranqphoat@gmail.com
    password: hamo tajp zwer rwxr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceMultivendor
    username: root
    password: 2202phoaT
    dll-auto: update

server:
  port: 8080
