spring:
  application:
    name: ecommerce-Multivendor


  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceMultivendor
    username: root
    password: 2202phoaT
    dll-auto: update

server:
  port: 8080
